on:
  push:
    branches:
    - main
    paths:
    - "**.adoc"
    - "**.nix"
    - "**.png"
jobs:
  nixos-options-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |-
        sha256=$(nix-prefetch-url --type sha256 --unpack "https://github.com/schnusch/nixos-update-reminder/archive/$GITHUB_SHA.tar.gz")
        sed -e "s,@@commit@@,$GITHUB_SHA,g" -e "s,@@sha256@@,$sha256,g" -i doc/example.nix
    - run: >-
        nix-build
        -o doc/options.adoc
        doc/options.nix
        --argstr baseURL "https://github.com/schnusch/nixos-update-reminder/blob/$GITHUB_SHA/"
        -A optionsAsciiDoc
    - run: mkdir -p doc/html
    - run: nix run nixpkgs#asciidoctor -- -o doc/html/index.html doc/index.adoc
    - run: mv doc/screenshot.png doc/html/
    - uses: actions/upload-pages-artifact@v3
      id: deployment
      with:
        path: doc/html/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    needs: nixos-options-doc
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
